public class Main {
    public static void main(String [] args){
        System.out.println("******** TEST INTEGER ********");
        MyDeque<Integer> deque1 = new MyDeque<>(0);
        deque1.print();
        System.out.println("**** addFirst(1) ****");
        deque1.addFirst(1);
        deque1.print();
        System.out.println("**** offerFirst (2) ****");
        deque1.offerFirst(2);
        deque1.print();
        System.out.println("**** offerLast (3) ****");
        deque1.offerLast(3);
        deque1.print();
        System.out.println("**** addLast (5) ****");
        deque1.addLast(5);
        deque1.print();
        System.out.println("**** pollFirst ****");
        deque1.pollFirst();
        deque1.print();
        System.out.println("**** removeLast ****");
        deque1.removeLast();
        deque1.print();
        System.out.println("**** addLast (10) ****");
        deque1.addLast(10);
        deque1.print();
        System.out.println("**** removeFirst ****");
        deque1.removeFirst();
        deque1.print();
        System.out.println("**** addFirst (5) ****");
        deque1.addFirst(5);
        deque1.print();
        System.out.println("**** getFirst  ****");
        System.out.println(deque1.getFirst());
        System.out.println("**** getLast  ****");
        System.out.println(deque1.getLast());
        System.out.println("**** peekFirst  ****");
        System.out.println(deque1.peekFirst());
        System.out.println("**** peekLast  ****");
        System.out.println(deque1.peekLast());
        System.out.println("*** removeLastOccurrence (0)***");
        deque1.removeLastOccurrence(0);
        deque1.print();
        System.out.println("*** removeFirstOccurrence (3)***");
        deque1.removeLastOccurrence(3);
        deque1.print();
        System.out.println("\n");
        System.out.println("******** TEST DOUBLE ********");
        MyDeque<Double> deque2 = new MyDeque<>(0.0);
        deque2.print();
        System.out.println("**** addFirst(1.1) ****");
        deque2.addFirst(1.1);
        deque2.print();
        System.out.println("**** offerFirst (2.0) ****");
        deque2.offerFirst(2.0);
        deque2.print();
        System.out.println("**** offerLast (3.3) ****");
        deque2.offerLast(3.3);
        deque2.print();
        System.out.println("**** addLast (5.2) ****");
        deque2.addLast(5.2);
        deque2.print();
        System.out.println("**** pollFirst ****");
        deque2.pollFirst();
        deque2.print();
        System.out.println("**** removeLast ****");
        deque2.removeLast();
        deque2.print();
        System.out.println("**** addLast (10.1) ****");
        deque2.addLast(10.1);
        deque2.print();
        System.out.println("**** removeFirst ****");
        deque2.removeFirst();
        deque2.print();
        System.out.println("**** addFirst (5.4) ****");
        deque2.addFirst(5.4);
        deque2.print();
        System.out.println("**** getFirst  ****");
        System.out.println(deque2.getFirst());
        System.out.println("**** getLast  ****");
        System.out.println(deque2.getLast());
        System.out.println("**** peekFirst  ****");
        System.out.println(deque2.peekFirst());
        System.out.println("**** peekLast  ****");
        System.out.println(deque2.peekLast());
        System.out.println("*** removeLastOccurrence (0.0)***");
        deque2.removeLastOccurrence(0.0);
        deque2.print();
        System.out.println("*** removeFirstOccurrence (3.3)***");
        deque2.removeLastOccurrence(3.3);
        deque2.print();
    }
}
