public class Main {
    public static void main(String [] args){
        System.out.println("\n****** FIRST GRAPH (UNDIRECTED) ******\n");
        ListGraph graph1 = new ListGraph(5,false);
        graph1.insert(new Edge(0,1,8));
        graph1.insert(new Edge(1,0,7));
        graph1.insert(new Edge(1,4,2));
        graph1.insert(new Edge(3,0,4));
        graph1.insert(new Edge(4,0,1));
        graph1.insert(new Edge(4,2,5));
        graph1.insert(new Edge(4,3,6));
        System.out.println(graph1.toString());
        System.out.println("\n*** Depth First Search 3 ***\n");
        graph1.depthFirstSearch(3);
        System.out.println("\n*** Breadth First Search 3 ***\n");
        graph1.breadthFirstSearch(3);
        System.out.println("\n*** Depth First Search 4 ***\n");
        graph1.depthFirstSearch(4);
        System.out.println("\n*** Breadth First Search 4 ***\n");
        graph1.breadthFirstSearch(4);
        System.out.println("\n*** REMOVE VERTEX 3 \n***");
        graph1.removeVertex(3);
        System.out.println(graph1.toString());
        System.out.println("\n*** REMOVE EDGE 4->0 \n***");
        graph1.removeEdge(new Edge(4,0));
        System.out.println(graph1.toString());

        System.out.println("\n****** SECOND GRAPH (DIRECTED) ******\n");
        ListGraph graph2 = new ListGraph(5,true);
        graph2.insert(new Edge(0,1,8));
        graph2.insert(new Edge(1,0,7));
        graph2.insert(new Edge(1,4,2));
        graph2.insert(new Edge(3,0,4));
        graph2.insert(new Edge(4,0,1));
        graph2.insert(new Edge(4,2,5));
        graph2.insert(new Edge(4,3,6));
        System.out.println(graph2.toString());
        System.out.println("\n*** Depth First Search 3 ***\n");
        graph2.depthFirstSearch(3);
        System.out.println("\n*** Breadth First Search 3 ***\n");
        graph2.breadthFirstSearch(3);
        System.out.println("\n*** Depth First Search 4 ***\n");
        graph2.depthFirstSearch(4);
        System.out.println("\n*** Breadth First Search 4 ***\n");
        graph2.breadthFirstSearch(4);
        System.out.println("\n*** REMOVE VERTEX 3 ***\n");
        graph2.removeVertex(3);
        System.out.println(graph2.toString());
        System.out.println("\n*** REMOVE EDGE 4->0 ***\n");
        graph2.removeEdge(new Edge(4,0));
        System.out.println(graph2.toString());

        System.out.println("\n****** THIRD GRAPH (DIRECTED) ******\n");
        ListGraph graph3 = new ListGraph(8,true);
        graph3.insert(new Edge(0,7,8));
        graph3.insert(new Edge(5,3,7));
        graph3.insert(new Edge(3,4,2));
        graph3.insert(new Edge(3,3,4));
        graph3.insert(new Edge(3,1,4));
        graph3.insert(new Edge(3,0,4));
        graph3.insert(new Edge(3,2,4));
        graph3.insert(new Edge(4,3,4));
        graph3.insert(new Edge(6,7,1));
        graph3.insert(new Edge(6,3,1));
        graph3.insert(new Edge(6,0,5));
        graph3.insert(new Edge(2,6,5));
        graph3.insert(new Edge(1,3,6));
        graph3.insert(new Edge(0,1,6));
        System.out.println(graph3.toString());
        System.out.println("\n***Depth First Search 3***");
        graph3.depthFirstSearch(3);
        System.out.println("\n***Breadth First Search 3***");
        graph3.breadthFirstSearch(3);
        System.out.println("\n***Depth First Search 6***");
        graph3.depthFirstSearch(6);
        System.out.println("\n***Breadth First Search 6***");
        graph3.breadthFirstSearch(6);
        System.out.println("\n*** REMOVE VERTEX 3 ***\n");
        graph3.removeVertex(3);
        System.out.println(graph3.toString());
        System.out.println("\n*** REMOVE EDGE 6->0 ***\n");
        graph3.removeEdge(new Edge(6,0));
        System.out.println(graph3.toString());
    }
}
